# Generated by Django 3.1.7 on 2021-03-30 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('medicalNumber', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('educationDegree', models.CharField(max_length=100)),
                ('medicalExpertise', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('1', 'User'), ('2', 'Doctor')], max_length=8)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitDate', models.DateField()),
                ('visitTime', models.TimeField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_example.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_example.userpanel')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='favoriteDoctors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to='user_example.userpanel'),
        ),
    ]
