# Generated by Django 3.1.7 on 2021-03-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='favoriteDoctors',
        ),
        migrations.AddField(
            model_name='userpanel',
            name='favoriteDoctors',
            field=models.ManyToManyField(to='user_example.Doctor'),
        ),
    ]
