# Generated by Django 3.1.7 on 2021-03-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0003_auto_20210330_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpanel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
